[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = "exec 'source' g:pluginDir . 'vim-go.vim'"
hook_post_update = '''
:GoUpdateBinaries
'''

[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = ['go']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
let g:vim_jsx_pretty_enable_jsx_highlight = 0
let g:vim_jsx_pretty_colorful_config = 1
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft= ['toml']

[[plugins]]
repo = 'maralla/vim-toml-enhance'
on_ft = ['toml']
depends = 'cespare/vim-toml'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = "exec 'source' g:pluginDir . 'vimtex.vim'"

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']
hook_add = "exec 'source' g:pluginDir . 'dart-vim-plugin.vim'"

[[plugins]]
repo =  'neovimhaskell/haskell-vim'
on_ft = ['haskell']
hook_add = "exec 'source' g:pluginDir . 'haskell-vim.vim'"

#[[plugins]]
#repo = 'ndmitchell/ghcid',
#on_ft= ['haskell']

[[plugins]]
repo = 'vim-pandoc/vim-pandoc'
on_ft = ['markdown']
hook_add = '''
" enable tex
let g:tex_conceal = ""
let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'vim-pandoc/vim-pandoc-syntax'
on_ft = ['markdown']
hook_add = 'let g:pandoc#syntax#conceal#use = 0'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']
hook_add = "exec 'source' g:pluginDir . 'vim-fish.vim'"

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_map = ['<Leader>cc', '<leader>cn', '<leader>c<space>', '<leader>cm', '<leader>ci', '<leader>cs', '<leader>cy', '<leader>c$', '<leader>cA', '<leader>ca', '<leader>cl', '<leader>cb', '<leader>cu']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle','NERDTreeFind','NERDTree']
