[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'bling/vim-airline'
hook_add = "exec 'source' g:pluginDir . 'vim-airline.vim'"

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = "exec 'source' g:pluginDir . 'fzf.vim.vim'"

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = "exec 'source' g:pluginDir . 'ale.vim'"

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = "exec 'source' g:pluginDir . 'coc.nvim.vim'"

[[plugins]]
repo = 'tpope/vim-sensible'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

# send to repl in terminal
[[plugins]]
repo = 'jalvesaq/vimcmdline'
hook_add = "exec 'source' g:pluginDir . 'vimcmdline.vim'"

[[plugins]]
repo = 'farmergreg/vim-lastplace'
hook_add = "let g:lastplace_ignore_buftype = 'quickfix,nofile,help,term'"

[[plugins]]
repo = 'unblevable/quick-scope'

#[[plugins]]
#repo = 'joom/latex-unicoder.vim'
#hook_add = "exec 'source' g:pluginDir . 'latex-unicoder.vim'"

[[plugins]]
repo = 'Yilin-Yang/vim-markbar'
hook_add = 'map <Leader>m <Plug>ToggleMarkbar'

# text objects (line w/o newline)
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-line'
hook_post_source = "exec 'source' g:pluginDir . 'vim-textobj-line.vim'"

[[plugins]]
repo = 'fidian/hexmode'
hook_post_source = "let g:hexmode_patterns = '*.bin,*.exe,*.dat,*.o,*.so'"

[[plugins]]
repo = 'triglav/vim-visual-increment'

[[plugins]]
repo = 'wesQ3/vim-windowswap'

# aligning (after the fact)
[[plugins]]
repo = 'godlygeek/tabular'

# pair brackets
[[plugins]]
repo = 'tmsvg/pear-tree'
hook_post_source = "exec 'source' g:pluginDir . 'pear-tree.vim'"

# case preserving subsitution
[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'salsifis/vim-transpose'

[[plugins]]
repo = 'airblade/vim-rooter'
hook_add = '''
let g:rooter_use_lcd = 1
let g:rooter_patterns = ['stack.yaml', 'pom.xml', 'build.gradle']
'''

[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'
hook_post_source = "exec 'source' g:pluginDir . 'julia-vim.vim'"

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'jvirtanen/vim-hcl'

[[plugins]]
repo = 'rbong/vim-flog'

[[plugins]]
repo = 'wellle/targets.vim'

[[plugins]]
repo = 'tpope/vim-eunuch'

[[plugins]]
repo = 'rbgrouleff/bclose.vim'

[[plugins]]
repo = 'ptzz/lf.vim'
depends = 'rbgrouleff/bclose.vim'
hook_add = '''
let g:lf_replace_netrw = 1
let g:lf_command_override = 'lf -command "set hidden"'
let g:lf_map_keys = 0
noremap <leader>l :Lf<CR>
cnoreabbrev L Lf
'''

[[plugins]]
repo = 'inkarkat/vim-ingo-library'

[[plugins]]
repo = 'inkarkat/vim-SearchHighlighting'
depends = 'inkarkat/vim-ingo-library'

[[plugins]]
repo = 'inkarkat/vim-SearchPosition'
depends = 'inkarkat/vim-ingo-library'

[[plugins]]
repo = 'arp242/jumpy.vim'
hook_add = '''
autocmd Filetype ruby call jumpy#map('\v^\s*(class|module|def)')
autocmd Filetype toml call jumpy#map('\v^\s\[\[')
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'jeetsukumaran/vim-indentwise'

[[plugins]]
repo = 'meain/vim-package-info'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = '''
set termguicolors
lua require'colorizer'.setup()
'''

[[plugins]]
repo = 'idanarye/vim-merginal'

[[plugins]]
repo = 'psliwka/vim-smoothie'

[[plugins]]
repo = 'conweller/findr.vim'

[[plugins]]
repo = 'zimbatm/haproxy.vim'

[[plugins]]
repo = 'junegunn/vim-emoji'
